site_name: grnndata
theme: 
  name: readthedocs
  # analytics:
    # gtag: G-ABC123
site_url: https://cantinilab.github.io/GRnnData
nav:
  - Home: index.md
  - example notebook: notebooks/example.ipynb
  - documentation:
    - utils: utils.md
    - GRNAnnData: grnanndata.md
plugins: 
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_root_heading: true
            show_source: true
            summary: true
            merge_init_into_class: true
            show_signature: false
            do_heading: true
      default_handler: python
  - git-revision-date-localized
  - git-authors
  - mkdocs-jupyter:
      include_source: True
      include_requirejs: true